name: Deploy createBuiltTiles

on:
  push:
    paths:
      - 'tasks/createBuiltTiles/**'
      - '.github/workflows/createBuiltTiles.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create Compute Engine Instance
        run: |
          # Check if the VM exists
          gcloud compute instances list --filter="name=nw-analysis-vm-built" | grep "nw-analysis-vm-built"
          VM_EXISTS=$?  # Exit status of grep (0 if found, 1 if not found)
          
          # Create the VM if it doesn't exist
          if [ "$VM_EXISTS" -ne "0" ]; then
            gcloud compute instances create nw-analysis-vm-built \
              --zone=europe-west9-a \
              --machine-type=e2-standard-8 \
              --image=debian-11-bullseye-v20230629 \
              --image-project=debian-cloud
          fi
        
      - name: Upload Service Account Key to VM
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud compute scp key.json nw-analysis-vm-built:~/key.json --zone=europe-west9-a
          rm key.json

          - name: SSH and Deploy
          run: |
            # Wait for the VM to be fully initialized
            sleep 60
            gcloud compute ssh nw-analysis-vm-built --zone=europe-west9-a --command "
              # Update package information
              sudo apt-get update
        
              # Install Git
              sudo apt-get install -y git
        
              # Install Docker
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
              sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
              sudo apt-get update
              sudo apt-get install -y docker-ce
        
              # Allow the current user to run Docker commands without sudo
              sudo usermod -aG docker $USER
        
              # Dployment logic
              rm -rf ~/naturewatch-analysis 
              git clone https://github.com/marynvdl/naturewatch-analysis 
              cd ~/naturewatch-analysis/tasks/createBuiltTiles 
              chmod +x deploy.sh 
              ./deploy.sh
            "

      - name: Delete Compute Engine Instance
        if: success() # This ensures that the VM is deleted only if the previous steps were successful.
        run: |
          gcloud compute instances delete nw-analysis-vm-built --zone=europe-west9-a --quiet
