name: Deploy createBuiltTiles

on:
  push:
    paths:
      - 'tasks/createBuiltTiles/**'
      - '.github/workflows/createBuiltTiles.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create Compute Engine Instance
        run: |
          gcloud compute instances create nw-analysis-vm-built \
            --zone=europe-west9-a \
            --machine-type=e2-standard-8 \
            --image=debian-11-bullseye-v20230629 \
            --image-project=debian-cloud

      - name: Upload Service Account Key to VM
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud compute scp key.json nw-analysis-vm-built:~/key.json --zone=europe-west9-a
          rm key.json

      - name: SSH and Deploy
        run: |
          # Wait for the VM to be fully initialized
          sleep 60
          gcloud compute ssh nw-analysis-vm-built --zone=europe-west9-a --command "sudo apt-get update && sudo apt-get install -y git && rm -rf ~/naturewatch-analysis && git clone https://github.com/marynvdl/naturewatch-analysis && cd ~/naturewatch-analysis/tasks/createBuiltTiles && chmod +x deploy.sh && ./deploy.sh"

      - name: Delete Compute Engine Instance
        if: success() # This ensures that the VM is deleted only if the previous steps were successful.
        run: |
          gcloud compute instances delete nw-analysis-vm-built --zone=europe-west9-a --quiet
