name: Deploy createBuiltTiles

on:
  push:
    paths:
      - 'tasks/createBuiltTiles/**'
      - '.github/workflows/createBuiltTiles.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create Compute Engine Instance (if it doesn't exist)
        run: |
          set -e
          INSTANCE_NAME="nw-analysis-vm-built"
          ZONE="europe-west4-a"
          
          # Check if the instance exists
          if ! gcloud compute instances describe $INSTANCE_NAME --zone=$ZONE > /dev/null 2>&1; then
            echo "Instance does not exist. Creating..."
            gcloud compute instances create $INSTANCE_NAME \
              --zone=$ZONE \
              --machine-type=e2-standard-4 \
              --image=debian-11-bullseye-v20230629 \
              --image-project=debian-cloud
          else
            echo "Instance already exists. Skipping creation."
          fi
        
      - name: Upload Service Account Key to VM
        run: |
          cat <<-EOM >key.json
          ${{ secrets.GCP_SA_KEY_FORMATTED }}
          EOM
          gcloud compute scp --verbosity=debug key.json nw-analysis-vm-built:~/key.json --zone=$ZONE
          rm key.json

      - name: SSH and Setup Docker
        run: |
          # Wait for the VM to be initialized
          sleep 60
          gcloud compute ssh nw-analysis-vm-built --zone=$ZONE --command "
            # Update package information
            sudo apt-get update
      
            # Install Git
            sudo apt-get install -y git
      
            # Install Docker
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
            sudo apt-get update
            sudo apt-get install -y docker-ce
      
            # Allow the current user to run Docker commands without sudo
            sudo usermod -aG docker $USER
          "
        
      - name: SSH and Deploy
        run: |
          gcloud compute ssh nw-analysis-vm-built --zone=$ZONE --command "
            # Deployment logic
            rm -rf ~/naturewatch-analysis 
            git clone https://github.com/marynvdl/naturewatch-analysis 
            cd ~/naturewatch-analysis/tasks/createBuiltTiles 
            chmod +x deploy.sh 
            ./deploy.sh
          "
